// Number of times we're going to loop

var number = 5;

// Variable inputField is created & displayed by the id "num-loops" in the html file
var inputField = document.getElementById("num-loops");
//  Variable counter is created & displayed by the id "counter" in the html file
var counter = document.getElementById("counter");


// Create a function called loopClick
function loopClick() {
	// number is generated by the value given by the inputField
	number = inputField.value;
	// clears the list of numbers every time you enter in a new number into the inputField
	counter.innerHTML = "";
	// for (every index while the index is less than the number given, increment and loop through...)
	for (var i=0; i < number; i++) {
		// display each index listed, using a line break to display each number on a new line
		counter.innerHTML += i + "<br/>";

	};
};
// Create a function called dice
function dice() {

	var roll = inputField.value;
	counter.innerHTML = "";
	
	for (var i=0; i < roll; i++) {	
		
		var randNum = Math.ceil(Math.random() * 6);  
		counter.innerHTML += "<img src='dice/" + randNum + ".png' alt='A die.'/><br/>";


	};

};

document.getElementById("loop-btn").onclick = dice;




// document.getElementById("loop-btn").onlick = function (){
// // build in method that takes in a passed string(id) that should reference an id on your HTML

// 	number = inputField.value;

// 	for (var i=0; i < number; i++) {

// 		console.log(i);
// 	};
// };